"""Initial schema: profiles, medications, schedules, dose_logs.

Every table gets row-level security enabled with no policies. Supabase exposes
the public schema over REST to anyone holding the publishable key that ships
inside the app; RLS-without-policies makes that key useless for reading data.
The API connects as `postgres`, which bypasses RLS.

Revision ID: 8c51e737518c
Revises:
Create Date: 2026-09-11 17:25:29.959648

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c51e737518c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("tz", sa.String(length=64), server_default="UTC", nullable=False),
        sa.Column(
            "missed_grace_minutes", sa.Integer(), server_default=sa.text("120"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "medications",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("strength", sa.String(length=60), nullable=True),
        sa.Column("form", sa.String(length=20), server_default="tablet", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "form IN ('tablet', 'capsule', 'liquid', 'injection', 'drops', 'inhaler', 'other')",
            name="medications_form_check",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_medications_user_id", "medications", ["user_id"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column(
            "times_of_day",
            postgresql.ARRAY(sa.Time()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "days_of_week",
            postgresql.ARRAY(sa.SmallInteger()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("interval", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_doses", sa.Integer(), nullable=True),
        sa.Column("tz", sa.String(length=64), nullable=False),
        sa.Column("dose_amount", sa.Numeric(precision=8, scale=3), nullable=False),
        sa.Column("dose_unit", sa.String(length=20), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.Column("replaces_schedule_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('daily', 'weekly', 'every_n_days', 'every_n_hours', 'as_needed')",
            name="schedules_kind_check",
        ),
        sa.CheckConstraint(
            "ends_at IS NULL OR ends_at > starts_at", name="schedules_ends_after_start"
        ),
        sa.CheckConstraint("interval >= 1", name="schedules_interval_check"),
        sa.ForeignKeyConstraint(["medication_id"], ["medications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["replaces_schedule_id"], ["schedules.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_schedules_medication_id", "schedules", ["medication_id"], unique=False)
    op.create_index("ix_schedules_user_id", "schedules", ["user_id"], unique=False)
    op.create_table(
        "dose_logs",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("medication_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=20), server_default="app", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('app', 'notification', 'web')", name="dose_logs_source_check"
        ),
        sa.CheckConstraint("status IN ('taken', 'skipped')", name="dose_logs_status_check"),
        sa.ForeignKeyConstraint(["medication_id"], ["medications.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["schedule_id"], ["schedules.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "schedule_id", "scheduled_at", name="uq_dose_logs_schedule_scheduled_at"
        ),
    )
    op.create_index(
        "ix_dose_logs_user_scheduled_at", "dose_logs", ["user_id", "scheduled_at"], unique=False
    )
    # ### end Alembic commands ###

    for table in ("profiles", "medications", "schedules", "dose_logs", "alembic_version"):
        op.execute(f"ALTER TABLE public.{table} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_dose_logs_user_scheduled_at", table_name="dose_logs")
    op.drop_table("dose_logs")
    op.drop_index("ix_schedules_user_id", table_name="schedules")
    op.drop_index("ix_schedules_medication_id", table_name="schedules")
    op.drop_table("schedules")
    op.drop_index("ix_medications_user_id", table_name="medications")
    op.drop_table("medications")
    op.drop_table("profiles")
    # ### end Alembic commands ###
    op.execute("ALTER TABLE public.alembic_version DISABLE ROW LEVEL SECURITY")
