/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_me_patch"];
        trace?: never;
    };
    "/medications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Medications */
        get: operations["list_medications_medications_get"];
        put?: never;
        /** Create Medication */
        post: operations["create_medication_medications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/medications/{medication_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Medication */
        get: operations["read_medication_medications__medication_id__get"];
        put?: never;
        post?: never;
        /**
         * Archive Medication
         * @description Archive, never delete: history keeps referring to it.
         */
        delete: operations["archive_medication_medications__medication_id__delete"];
        options?: never;
        head?: never;
        /** Update Medication */
        patch: operations["update_medication_medications__medication_id__patch"];
        trace?: never;
    };
    "/medications/{medication_id}/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Schedule
         * @description A second schedule for the same medicine, e.g. a different dose at night.
         */
        post: operations["add_schedule_medications__medication_id__schedules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{schedule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Replace Schedule
         * @description 'Edit' = end the old version now and start a new one that points back at it.
         */
        put: operations["replace_schedule_schedules__schedule_id__put"];
        post?: never;
        /** End Schedule */
        delete: operations["end_schedule_schedules__schedule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Doses
         * @description Doses scheduled in [from, to). The app passes the UTC bounds of its local
         *     day for Today, or now..now+14d to schedule reminders.
         */
        get: operations["list_doses_doses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doses/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Dose
         * @description Record what happened to a dose. Idempotent per (schedule, scheduled_at):
         *     logging the same dose twice updates the first record instead of duplicating
         *     it, so a notification action and a tap in the app can't disagree.
         */
        post: operations["log_dose_doses_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/doses/log/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Undo Log */
        delete: operations["undo_log_doses_log__log_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DoseInstanceOut
         * @description A computed dose: what to take, when, and what happened to it.
         */
        DoseInstanceOut: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Medication Name */
            medication_name: string;
            /** Strength */
            strength: string | null;
            /**
             * Form
             * @enum {string}
             */
            form: "tablet" | "capsule" | "liquid" | "injection" | "drops" | "inhaler" | "other";
            /** Dose Amount */
            dose_amount: string;
            /** Dose Unit */
            dose_unit: string;
            /** Instructions */
            instructions: string | null;
            /**
             * Scheduled At
             * Format: date-time
             */
            scheduled_at: string;
            status: components["schemas"]["DoseStatus"];
            log: components["schemas"]["DoseLogOut"] | null;
        };
        /** DoseLogIn */
        DoseLogIn: {
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /** Scheduled At */
            scheduled_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "taken" | "skipped";
            /** Taken At */
            taken_at?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Source
             * @default app
             * @enum {string}
             */
            source: "app" | "notification" | "web";
        };
        /** DoseLogOut */
        DoseLogOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Schedule Id
             * Format: uuid
             */
            schedule_id: string;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            /** Scheduled At */
            scheduled_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "taken" | "skipped";
            /** Taken At */
            taken_at: string | null;
            /** Note */
            note: string | null;
            /** Source */
            source: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * DoseStatus
         * @enum {string}
         */
        DoseStatus: "upcoming" | "due" | "taken" | "skipped" | "missed";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MedicationIn */
        MedicationIn: {
            /** Name */
            name: string;
            /** Strength */
            strength?: string | null;
            /**
             * Form
             * @default tablet
             * @enum {string}
             */
            form: "tablet" | "capsule" | "liquid" | "injection" | "drops" | "inhaler" | "other";
            /** Notes */
            notes?: string | null;
            schedule: components["schemas"]["ScheduleIn"];
        };
        /** MedicationOut */
        MedicationOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Strength */
            strength: string | null;
            /**
             * Form
             * @enum {string}
             */
            form: "tablet" | "capsule" | "liquid" | "injection" | "drops" | "inhaler" | "other";
            /** Notes */
            notes: string | null;
            /** Archived At */
            archived_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Schedules */
            schedules: components["schemas"]["ScheduleOut"][];
        };
        /** MedicationPatch */
        MedicationPatch: {
            /** Name */
            name?: string | null;
            /** Strength */
            strength?: string | null;
            /** Form */
            form?: ("tablet" | "capsule" | "liquid" | "injection" | "drops" | "inhaler" | "other") | null;
            /** Notes */
            notes?: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string | null;
            /** Tz */
            tz: string;
            /** Missed Grace Minutes */
            missed_grace_minutes: number;
        };
        /** ProfilePatch */
        ProfilePatch: {
            /** Display Name */
            display_name?: string | null;
            /** Tz */
            tz?: string | null;
            /** Missed Grace Minutes */
            missed_grace_minutes?: number | null;
        };
        /**
         * ScheduleIn
         * @description How the app describes a schedule. Dates and clock times are the user's
         *     local ones; the API converts them to instants using `tz`.
         */
        ScheduleIn: {
            kind: components["schemas"]["ScheduleKind"];
            /** Tz */
            tz: string;
            /**
             * Times Of Day
             * @default []
             */
            times_of_day: string[];
            /**
             * Days Of Week
             * @default []
             */
            days_of_week: number[];
            /**
             * Interval
             * @default 1
             */
            interval: number;
            /** Start Date */
            start_date?: string | null;
            /** First Dose At */
            first_dose_at?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Total Doses */
            total_doses?: number | null;
            /** Dose Amount */
            dose_amount: number | string;
            /** Dose Unit */
            dose_unit: string;
            /** Instructions */
            instructions?: string | null;
        };
        /**
         * ScheduleKind
         * @enum {string}
         */
        ScheduleKind: "daily" | "weekly" | "every_n_days" | "every_n_hours" | "as_needed";
        /** ScheduleOut */
        ScheduleOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Medication Id
             * Format: uuid
             */
            medication_id: string;
            kind: components["schemas"]["ScheduleKind"];
            /** Tz */
            tz: string;
            /** Times Of Day */
            times_of_day: string[];
            /** Days Of Week */
            days_of_week: number[];
            /** Interval */
            interval: number;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Ends At */
            ends_at: string | null;
            /** Total Doses */
            total_doses: number | null;
            /** Dose Amount */
            dose_amount: string;
            /** Dose Unit */
            dose_unit: string;
            /** Instructions */
            instructions: string | null;
            /** Replaces Schedule Id */
            replaces_schedule_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_me_me_get: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_me_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProfilePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_medications_medications_get: {
        parameters: {
            query?: {
                archived?: boolean;
            };
            header?: {
                "x-timezone"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_medication_medications_post: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_medication_medications__medication_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path: {
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_medication_medications__medication_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path: {
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_medication_medications__medication_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path: {
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MedicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_schedule_medications__medication_id__schedules_post: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path: {
                medication_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_schedule_schedules__schedule_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_schedule_schedules__schedule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path: {
                schedule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_doses_doses_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: {
                "x-timezone"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoseInstanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_dose_doses_log_post: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DoseLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoseLogOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_log_doses_log__log_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-timezone"?: string | null;
            };
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
